FROM node:18-slim

# เพิ่ม tools ที่จำเป็น (ถ้าต้องการ)
WORKDIR /app

COPY package.json package.json
RUN npm install --production

# คัดลอกโค้ดและโฟลเดอร์ model (model.json และ weights .bin)
COPY . .

EXPOSE 8080
CMD ["npm", "start"]